spring:
  application:
    name: proxy-gateway
  cloud:
    gateway:
      routes:
        - id: whoami
          uri: http://172.18.0.2
          predicates:
            - Path=/info
        - id: baeldung
          uri: https://baeldung.com
          predicates:
            - Path=/read
          filters:
            - RedirectTo=302, https://baeldung.com
        - id: one
          uri: https://httpbin.org/
          predicates:
            - Path=/get